[workspace]
members = [ "projects/complex",
    "projects/complex",
    "projects/logic_gates",
    "projects/word_counter",
    "projects/todo_list_parser", 
    "projects/macro_map", "projects/macro_exercises",
]
