[package]
name = "env_logger_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.6"
user_auth = {path = "../user_auth"}
log = { version = "0.4", features = ["release_max_level_error", "max_level_trace"] }
